export const words: string[] = [
    "apple", "ant", "art", "air", "arm", "ask", "age", "arch", "attic", "amber",
    "banana", "book", "ball", "bat", "boat", "bag", "breeze", "bark", "bowl", "butter",
    "cat", "car", "cake", "cup", "coat", "cloud", "candle", "crab", "coin", "cousin",
    "dog", "doll", "desk", "duck", "drum", "dawn", "deer", "dance", "dive", "dough",
    "elephant", "egg", "ear", "edge", "earth", "echo", "exit", "even", "eel", "eagle",
    "fish", "fan", "frog", "fire", "fork", "face", "field", "fence", "fry", "foot",
    "goat", "game", "gift", "gown", "glove", "globe", "grain", "gate", "glass", "gaze",
    "hat", "hand", "house", "hill", "hive", "horse", "heart", "hatch", "honey", "hope",
    "igloo", "ice", "ink", "island", "iron", "inch", "idea", "imp", "ivy", "invite",
    "jacket", "jam", "jungle", "jump", "joke", "jet", "jar", "jewel", "jigsaw", "judge",
    "kite", "key", "king", "kitchen", "kick", "kid", "knot", "kale", "knee", "kitten",
    "lion", "lamp", "leaf", "lake", "leg", "log", "lawn", "lizard", "lace", "light",
    "mouse", "map", "mug", "mat", "moon", "meat", "moth", "muffin", "mop", "mango",
    "nose", "net", "nut", "nap", "napkin", "neck", "nail", "night", "news", "note",
    "owl", "ocean", "oak", "orange", "onion", "oval", "olive", "otter", "ore", "orbit",
    "pig", "pen", "piano", "pocket", "pool", "panda", "plate", "pear", "plum", "pillow",
    "queen", "quilt", "quail", "quick", "quiet", "quest", "quarry", "quasar", "quilt", "quench",
    "rose", "ring", "rock", "road", "rat", "row", "ribbon", "rain", "rocket", "rake",
    "snake", "star", "sock", "stick", "sail", "sand", "soup", "shelf", "sneeze", "sugar",
    "tiger", "tree", "table", "toy", "tune", "tide", "towel", "train", "taco", "tarp",
    "umbrella", "up", "unicorn", "utensil", "urn", "under", "unit", "urban", "utility", "unique",
    "vase", "van", "valley", "vowel", "viper", "vortex", "vision", "victory", "village", "vow",
    "whale", "window", "wolf", "wing", "whip", "wish", "water", "wool", "wallet", "wave",
    "xray", "xylophone", "xenon", "xerox", "xenophobia", "xmas", "xenophile", "xenolith", "xylem", "xenogeneic",
    "yak", "yarn", "yacht", "yellow", "yogurt", "yoke", "yell", "year", "yes", "yawn",
    "zebra", "zoo", "zip", "zest", "zone", "zinc", "zodiac", "zoom", "zenith", "zany"
]
